[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/drdave-teaching/OPIM5509Files/blob/main/OPIM5509_Module5_Files/Dave_s_GLoVE_Example.ipynb)

In [ ]:
!pip install tensorflow

In [ ]:
# link: https://machinelearningmastery.com/use-word-embedding-layers-deep-learning-keras/

# Example 3: Learning an embedding
from numpy import array
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.layers import Flatten
from tensorflow.keras.layers import Embedding

# define documents
# EXERCISE: write more here... you can even use a .csv file instad of typing manually...
docs = ['Well done!',
		'Good work',
		'Great effort',
		'nice work',
		'Excellent!',
		'Weak',
		'Poor effort!',
		'not good',
		'poor work',
		'Could have done better.']
# define class labels
labels = array([1,1,1,1,1,0,0,0,0,0])
# integer encode the documents
vocab_size = 50 # play with this...
encoded_docs = [one_hot(d, vocab_size) for d in docs]
print("===========================================================")
print("THESE ARE THE ENCODED DOCS")
print("===========================================================")
print(encoded_docs)
# pad documents to a max length of 4 words
# EXERCISE: play with the length of words, more or less... how does it chop them off?
max_length = 4
padded_docs = pad_sequences(encoded_docs, maxlen=max_length, padding='post')
print("===========================================================")
print("THESE ARE THE PADDED, ONE HOT DOCS")
print("===========================================================")
print(padded_docs)

# define the model
model = Sequential()
model.add(Embedding(vocab_size, 8, input_length=max_length))
model.add(Flatten())
model.add(Dense(1, activation='sigmoid'))

# compile the model
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

# summarize the model
print(model.summary())

# fit the model
model.fit(padded_docs, labels, epochs=50, verbose=0)

# evaluate the model
loss, accuracy = model.evaluate(padded_docs, labels, verbose=0)
print('Accuracy: %f' % (accuracy*100))


THESE ARE THE ENCODED DOCS
[[37, 8], [48, 41], [10, 48], [26, 41], [7], [47], [12, 48], [14, 48], [12, 41], [45, 41, 8, 49]]
THESE ARE THE PADDED, ONE HOT DOCS
[[37  8  0  0]
 [48 41  0  0]
 [10 48  0  0]
 [26 41  0  0]
 [ 7  0  0  0]
 [47  0  0  0]
 [12 48  0  0]
 [14 48  0  0]
 [12 41  0  0]
 [45 41  8 49]]
Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding (Embedding)        (None, 4, 8)              400       
_________________________________________________________________
flatten (Flatten)            (None, 32)                0         
_________________________________________________________________
dense (Dense)                (None, 1)                 33        
Total params: 433
Trainable params: 433
Non-trainable params: 0
_________________________________________________________________
None
Accuracy: 89.999998


In [ ]:
# this also looks like a great example - visualizing the embeddings is key!
# link: https://towardsdatascience.com/neural-network-embeddings-explained-4d028e6f0526

In [ ]:
# get access to the weights! since we made them 8-dimensional, each word is 8 dimensional!

# link: https://stackoverflow.com/questions/51235118/how-to-get-word-vectors-from-keras-embedding-layer

# access the embedding layer through the constructed model
# first `0` refers to the position of embedding layer in the `model`
embeddings = model.layers[0].get_weights()[0]

# this is the shape of the embeddings
print(embeddings.shape)

# these are the embeddings
print(embeddings)

(50, 8)
[[ 0.00600388  0.02085383 -0.05811397 -0.07010853  0.09008072  0.02755397
  -0.09322599 -0.09458238]
 [ 0.0338014  -0.03944095 -0.03014462 -0.00836288 -0.03932029  0.04680338
   0.01988541 -0.04505447]
 [ 0.00681535 -0.00395079  0.00187421 -0.03507826 -0.04603286  0.02706984
   0.03837525 -0.04505229]
 [-0.04190177  0.00591962  0.00293298 -0.04113539  0.04500247 -0.00211649
   0.02533776 -0.04189419]
 [ 0.027567   -0.01522393  0.00827737  0.04283581  0.0306324  -0.04677843
  -0.03341582  0.00299717]
 [-0.01506797 -0.03601909 -0.03489845  0.03185412  0.00814904 -0.01588036
  -0.03804338  0.035438  ]
 [ 0.03422118 -0.04536521 -0.03663887 -0.01247614  0.02244287 -0.02443531
   0.01696977  0.01002834]
 [ 0.05501074  0.06826174  0.0795456   0.07989514 -0.05112276 -0.01322161
  -0.10497637  0.07594394]
 [-0.04181968 -0.03773943 -0.00233484  0.04760867 -0.08919214 -0.05641707
  -0.06280068 -0.01243507]
 [-0.01222948  0.01491017 -0.04054014  0.03539288 -0.04779878  0.0332469
  -0.00990

In [ ]:
# do a lookup for each word
embeddings[34]

array([ 0.04602985,  0.01445813,  0.00545962,  0.00603942, -0.02537164,
        0.04584457,  0.04338105, -0.03723725], dtype=float32)

In [ ]:
# # Link to the glove.6B.100d.txt file on Github
# "https://github.com/drdave-teaching/OPIM5509Files/raw/refs/heads/main/OPIM5509_Module5_Files/glove.6B.100d.txt"

In [ ]:
# https://drive.google.com/file/d/1OZ9fiJCZV1mIpGvw_mS4ZJKZS-QaoJ5S/view?usp=sharing
!gdown 1OZ9fiJCZV1mIpGvw_mS4ZJKZS-QaoJ5S

Downloading...
From (original): https://drive.google.com/uc?id=1OZ9fiJCZV1mIpGvw_mS4ZJKZS-QaoJ5S
From (redirected): https://drive.google.com/uc?id=1OZ9fiJCZV1mIpGvw_mS4ZJKZS-QaoJ5S&confirm=t&uuid=432f0b87-8da3-466a-9d99-50827c2c40f1
To: /content/glove.6B.100d.txt
100% 347M/347M [00:09<00:00, 37.0MB/s]


In [ ]:
!pip install tensorflow

In [ ]:
# now let's try using GLoVE (make sure this is on your computer!) - this can go into a different script?
# link: https://machinelearningmastery.com/use-word-embedding-layers-deep-learning-keras/

# load the whole embedding into memory
from numpy import array
from numpy import asarray
from numpy import zeros
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.layers import Flatten
from tensorflow.keras.layers import Embedding

embeddings_index = dict()

f = open("/content/glove.6B.100d.txt")
for line in f:
	values = line.split()
	word = values[0]
	coefs = asarray(values[1:], dtype='float32')
	embeddings_index[word] = coefs
f.close()
print('Loaded %s word vectors.' % len(embeddings_index))


# define documents
docs = ['Well done!',
		'Good work',
		'Great effort',
		'nice work',
		'Excellent!',
		'Weak',
		'Poor effort!',
		'not good',
		'poor work',
		'Could have done better.']
# define class labels
labels = array([1,1,1,1,1,0,0,0,0,0])
# prepare tokenizer - we can break each out into a different cell in class
t = Tokenizer()
t.fit_on_texts(docs)
vocab_size = len(t.word_index) + 1
# integer encode the documents
encoded_docs = t.texts_to_sequences(docs)
print(encoded_docs)
# pad documents to a max length of 4 words
max_length = 4
padded_docs = pad_sequences(encoded_docs, maxlen=max_length, padding='post')
print(padded_docs)

# create a weight matrix for words in training docs
embedding_matrix = zeros((vocab_size, 100))
for word, i in t.word_index.items():
	embedding_vector = embeddings_index.get(word)
	if embedding_vector is not None:
		embedding_matrix[i] = embedding_vector
# define model
model = Sequential()
e = Embedding(vocab_size, 100, weights=[embedding_matrix], input_length=4, trainable=False)
model.add(e)
model.add(Flatten())
model.add(Dense(1, activation='sigmoid'))
# compile the model
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])
# summarize the model
print(model.summary())
# fit the model
model.fit(padded_docs, labels, epochs=50, verbose=0)
# evaluate the model
loss, accuracy = model.evaluate(padded_docs, labels, verbose=0)
print('Accuracy: %f' % (accuracy*100))

Loaded 400000 word vectors.
[[6, 2], [3, 1], [7, 4], [8, 1], [9], [10], [5, 4], [11, 3], [5, 1], [12, 13, 2, 14]]
[[ 6  2  0  0]
 [ 3  1  0  0]
 [ 7  4  0  0]
 [ 8  1  0  0]
 [ 9  0  0  0]
 [10  0  0  0]
 [ 5  4  0  0]
 [11  3  0  0]
 [ 5  1  0  0]
 [12 13  2 14]]


/usr/local/lib/python3.10/dist-packages/keras/src/layers/core/embedding.py:90: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ embedding (Embedding)                │ ?                           │           1,500 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ flatten (Flatten)                    │ ?                           │     0 (unbuilt) │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense (Dense)                        │ ?                           │     0 (unbuilt) │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 1,500 (5.86 KB)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 1,500 (5.86 KB)

None
Accuracy: 100.000000


In [ ]:
# look at the embedding matrix
print(embedding_matrix.shape) # 15 words, each are 100 dimensions

# these are all of the words and their index... you can look back at the table!
print(t.word_index.items())

# in comparison, this is the ordered dictionary - word and frequency associated with it!
print(t.word_counts)

(15, 100)
dict_items([('work', 1), ('done', 2), ('good', 3), ('effort', 4), ('poor', 5), ('well', 6), ('great', 7), ('nice', 8), ('excellent', 9), ('weak', 10), ('not', 11), ('could', 12), ('have', 13), ('better', 14)])
OrderedDict([('well', 1), ('done', 2), ('good', 2), ('work', 3), ('great', 1), ('effort', 2), ('nice', 1), ('excellent', 1), ('weak', 1), ('poor', 2), ('not', 1), ('could', 1), ('have', 1), ('better', 1)])


In [ ]:
# this is the embedding associated with each one!
# note how it goes from 1 to 14, does not include 0 or 15
# you can verify this by looking at t.word_index.items()

# this is the word embedding for "work"
embedding_matrix[1]

array([-1.16190001e-01,  4.54470009e-01, -6.92160010e-01,  3.45799997e-02,
        2.63480008e-01, -3.81390005e-01, -2.27899998e-01,  3.72330010e-01,
       -2.05789998e-01,  2.90199995e-01,  1.21140003e-01, -4.27289993e-01,
        5.55729985e-01, -9.42860022e-02, -4.99669999e-01, -2.94779986e-01,
        7.41090000e-01,  2.51910001e-01, -2.74679989e-01,  2.31910005e-01,
        3.82039999e-03,  4.52519991e-02,  2.49699995e-01, -4.15789992e-01,
        3.13069999e-01, -5.84959984e-01, -3.27389985e-01, -6.61889970e-01,
        1.49090007e-01, -2.57710010e-01, -9.48580027e-01,  4.18089986e-01,
       -2.95379996e-01, -4.27110009e-02, -6.99699998e-01,  5.78920007e-01,
       -6.92709982e-02, -3.96329984e-02, -5.64630004e-03, -2.96160012e-01,
       -5.74479997e-01,  1.60099998e-01, -1.06710002e-01,  1.00960001e-01,
       -4.29560006e-01, -2.77850002e-01, -3.00170004e-01, -6.95370018e-01,
        1.79649994e-01, -4.67229992e-01,  1.25110000e-01, -2.90220007e-02,
       -1.59740001e-01,  

In [ ]:
# we can also use a simpleRNN
# and we can also apply these to the IMDB dataset (tomorrow!)